version: '3'
services:
  app:
    build:
      context: ./site
    ports:
     - "80:80"
    volumes:
     - /assets/img:/app/source/images/portfolio/img
     - /assets/thumbnails:/app/source/images/portfolio/thumbnails
