version: '3'
services:
  app:
    build:
      context: ./site
    ports:
     - "80:80"
    volumes:
     - type: bind
       source: /assets/img
       target: /app/source/images/portfolio/img
     - type: bind
       source: /assets/thumbnails
       target: /app/source/images/portfolio/thumbnails
