source 'https://rubygems.org'

gem 'middleman', '~> 4.2.1'
gem 'middleman-autoprefixer', '~> 2.8'
gem "middleman-blog"

gem 'tzinfo-data', platforms: [:mswin, :mingw, :jruby]
gem 'wdm', '~> 0.1', platforms: [:mswin, :mingw]
gem 'tilt', '~> 2.0.8'
gem 'haml'

# For markdown
gem 'redcarpet', '~> 3.3', '>= 3.3.3'

# Summaries for the post
gem 'nokogiri'

#For minify
gem 'babel-transpiler'

#For nice output
gem 'colorize'